spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatisplus1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: sa123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package:
    xyz.fusheng.mybatisplus1.enums
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      #\u4E3B\u952E\u7C7B\u578B AUTO:"\u6570\u636E\u5E93ID\u81EA\u589E" INPUT:"\u7528\u6237\u8F93\u5165ID",ID_WORKER:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", UUID:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: AUTO
      #\u5B57\u6BB5\u7B56\u7565 IGNORED:"\u5FFD\u7565\u5224\u65AD"  NOT_NULL:"\u975E NULL \u5224\u65AD")  NOT_EMPTY:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: NOT_EMPTY
      #\u6570\u636E\u5E93\u7C7B\u578B
      db-type: MYSQL
